---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: performance-addon-operator
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - machineconfiguration.openshift.io
  resources:
    - kubeletconfigs
    - machineconfigpools
    - machineconfigs
  verbs:
    - '*'
- apiGroups:
    - node.k8s.io
  resources:
    - runtimeclasses
  verbs:
    - '*'
- apiGroups:
    - performance.openshift.io
  resources:
    - performanceprofiles
    - performanceprofiles/finalizers
    - performanceprofiles/status
  verbs:
    - '*'
- apiGroups:
    - tuned.openshift.io
  resources:
    - profiles
    - tuneds
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
rules:
  - apiGroups:
      - apps
    resourceNames:
      - performance-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
      - services/finalizers
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: performance-addon-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: performance-addon-operator
subjects:
- kind: ServiceAccount
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: performance-addon-operator
subjects:
- kind: ServiceAccount
  name: performance-addon-operator
  namespace: openshift-performance-addon-operator
